-- ============================================================================
-- Mẹ Yêu Bé V15.0.79 · Realtime Reliability & Conflict Guard
-- Database First · Relational Only · No legacy JSON runtime · No write queue
--
-- Mục tiêu:
--   1) Idempotency: cùng operation_id chỉ được COMMIT một lần.
--   2) Family revision guard: không âm thầm ghi đè khi thiết bị khác đã đổi DB.
--   3) Realtime signal có revision để client bỏ qua event cũ/trùng.
--   4) Presence nhẹ để hiển thị số thiết bị online, KHÔNG phát realtime business event.
--   5) CHECK constraints NOT VALID: bảo vệ dữ liệu mới mà không làm fail vì lịch sử cũ.
--
-- Yêu cầu: V15.0.76+ RPC myb_relational_apply_changes_v1576 / export_state_v1576
--          và V15.0.77 myb_realtime_events đã được cài.
-- Safe to run more than once.
-- ============================================================================

begin;

create extension if not exists pgcrypto;

-- --------------------------------------------------------------------------
-- 1. Family revision = số thứ tự commit nghiệp vụ của một family.
-- --------------------------------------------------------------------------
create table if not exists public.myb_family_runtime_state (
  family_id uuid primary key references public.families(id) on delete cascade,
  revision bigint not null default 0,
  last_operation_id uuid,
  last_device_key text,
  last_changed_at timestamptz,
  last_conflict_at timestamptz,
  conflict_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.myb_idempotent_operations (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families(id) on delete cascade,
  operation_id uuid not null,
  device_key text,
  base_revision bigint,
  applied_revision bigint,
  change_count int not null default 0,
  status text not null default 'processing',
  result jsonb not null default '{}'::jsonb,
  error text,
  attempt_count int not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  applied_at timestamptz,
  unique(family_id, operation_id)
);

create index if not exists idx_myb_idempotent_operations_family_created
  on public.myb_idempotent_operations(family_id, created_at desc);

alter table public.myb_family_runtime_state enable row level security;
alter table public.myb_idempotent_operations enable row level security;
revoke all on public.myb_family_runtime_state from anon, authenticated;
revoke all on public.myb_idempotent_operations from anon, authenticated;

-- --------------------------------------------------------------------------
-- 2. Realtime event thêm revision/op id. Không chứa dữ liệu nghiệp vụ.
-- --------------------------------------------------------------------------
create table if not exists public.myb_realtime_events (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  event_kind text not null default 'relational_write',
  created_at timestamptz not null default now()
);

alter table public.myb_realtime_events enable row level security;
drop policy if exists myb_realtime_events_read_signal on public.myb_realtime_events;
create policy myb_realtime_events_read_signal on public.myb_realtime_events
  for select to anon, authenticated using (true);
revoke insert, update, delete on public.myb_realtime_events from anon, authenticated;
grant select on public.myb_realtime_events to anon, authenticated;

alter table public.myb_realtime_events
  add column if not exists revision bigint,
  add column if not exists operation_id uuid;

create index if not exists idx_myb_realtime_events_family_revision
  on public.myb_realtime_events(family_id, revision desc)
  where revision is not null;

-- V15.0.77 trigger vẫn phục vụ thiết bị V15.0.78 trong lúc chuyển version.
-- Với write/presence V15.0.79, trigger này bỏ qua vì wrapper V15.0.79 tự emit
-- signal sau khi revision đã tăng.
create or replace function public.myb_emit_relational_realtime_v1577()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if nullif(current_setting('myb.v1579_operation_id', true), '') is not null
     or nullif(current_setting('myb.v1579_presence', true), '') is not null then
    return new;
  end if;

  insert into public.myb_realtime_events(family_id, event_kind, created_at)
  values (new.family_id, 'relational_write_legacy_client', now());

  if random() < 0.01 then
    delete from public.myb_realtime_events where created_at < now() - interval '30 days';
  end if;
  return new;
end;
$$;

revoke all on function public.myb_emit_relational_realtime_v1577() from public;

drop trigger if exists trg_myb_devices_realtime_v1577 on public.devices;
create trigger trg_myb_devices_realtime_v1577
after insert or update of last_seen_at on public.devices
for each row execute function public.myb_emit_relational_realtime_v1577();

do $$
begin
  if exists(select 1 from pg_publication where pubname='supabase_realtime')
     and not exists(
       select 1 from pg_publication_tables
       where pubname='supabase_realtime' and schemaname='public' and tablename='myb_realtime_events'
     ) then
    execute 'alter publication supabase_realtime add table public.myb_realtime_events';
  end if;
end $$;

-- --------------------------------------------------------------------------
-- 3. Export state + revision trong CÙNG một RPC đọc.
-- --------------------------------------------------------------------------
create or replace function public.myb_relational_export_state_v1579(p_sync_id text default 'main')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sync_id text := coalesce(nullif(p_sync_id,''),'main');
  v_family_id uuid := public.myb_stable_uuid('family:' || coalesce(nullif(p_sync_id,''),'main'));
  v_payload jsonb;
  v_revision bigint := 0;
  v_conflicts bigint := 0;
  v_last_changed timestamptz;
  v_last_conflict timestamptz;
  v_last_operation uuid;
  v_online int := 0;
  v_devices int := 0;
begin
  v_payload := public.myb_relational_export_state_v1576(v_sync_id);

  insert into public.myb_family_runtime_state(family_id, revision, created_at, updated_at)
  values(v_family_id, 0, now(), now())
  on conflict (family_id) do nothing;

  select revision, conflict_count, last_changed_at, last_conflict_at, last_operation_id
    into v_revision, v_conflicts, v_last_changed, v_last_conflict, v_last_operation
  from public.myb_family_runtime_state
  where family_id = v_family_id;

  select count(*)::int,
         count(*) filter (where deleted_at is null and last_seen_at >= now() - interval '3 minutes')::int
    into v_devices, v_online
  from public.devices
  where family_id = v_family_id and deleted_at is null;

  return coalesce(v_payload,'{}'::jsonb) || jsonb_build_object(
    'runtime_version','15.0.79',
    'revision',coalesce(v_revision,0),
    'conflict_count',coalesce(v_conflicts,0),
    'last_changed_at',v_last_changed,
    'last_conflict_at',v_last_conflict,
    'last_operation_id',v_last_operation,
    'device_count',coalesce(v_devices,0),
    'online_device_count',coalesce(v_online,0)
  );
end;
$$;

-- --------------------------------------------------------------------------
-- 4. Idempotent write + optimistic concurrency guard.
--    Toàn bộ chạy trong một DB transaction của RPC.
-- --------------------------------------------------------------------------
create or replace function public.myb_relational_apply_changes_v1579(
  p_sync_id text default 'main',
  p_device_key text default null,
  p_operation_id uuid default gen_random_uuid(),
  p_base_revision bigint default 0,
  p_changes jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sync_id text := coalesce(nullif(p_sync_id,''),'main');
  v_family_id uuid := public.myb_stable_uuid('family:' || coalesce(nullif(p_sync_id,''),'main'));
  v_current_revision bigint := 0;
  v_new_revision bigint := 0;
  v_existing_status text;
  v_existing_result jsonb;
  v_result jsonb;
  v_change_count int := case when jsonb_typeof(p_changes)='array' then jsonb_array_length(p_changes) else 0 end;
begin
  if p_operation_id is null then
    return jsonb_build_object('ok',false,'status','invalid_operation_id','message','operation_id không được null');
  end if;
  if jsonb_typeof(p_changes) is distinct from 'array' then
    return jsonb_build_object('ok',false,'status','invalid_changes','message','p_changes phải là JSON array');
  end if;

  -- Serialise tất cả write của cùng family.
  perform pg_advisory_xact_lock(hashtext(v_family_id::text));

  insert into public.families(id, sync_code, name, legacy_sync_id, created_at, updated_at, deleted_at)
  values(v_family_id, v_sync_id, 'Mẹ Yêu Bé', v_sync_id, now(), now(), null)
  on conflict (id) do update set updated_at=now(), deleted_at=null;

  insert into public.myb_family_runtime_state(family_id, revision, created_at, updated_at)
  values(v_family_id, 0, now(), now())
  on conflict (family_id) do nothing;

  -- Retry cùng operation_id sau timeout mạng => KHÔNG apply lại.
  select status, result
    into v_existing_status, v_existing_result
  from public.myb_idempotent_operations
  where family_id=v_family_id and operation_id=p_operation_id;

  if v_existing_status='applied' then
    return coalesce(v_existing_result,'{}'::jsonb) || jsonb_build_object(
      'ok',true,'status','already_applied','idempotent_replay',true,'operation_id',p_operation_id
    );
  elsif v_existing_status='conflict' then
    return coalesce(v_existing_result,'{}'::jsonb) || jsonb_build_object(
      'ok',false,'status','conflict','idempotent_replay',true,'operation_id',p_operation_id
    );
  end if;

  select revision into v_current_revision
  from public.myb_family_runtime_state
  where family_id=v_family_id
  for update;

  if coalesce(p_base_revision,0) <> coalesce(v_current_revision,0) then
    update public.myb_family_runtime_state
       set conflict_count=conflict_count+1,
           last_conflict_at=now(),
           updated_at=now()
     where family_id=v_family_id;

    v_result := jsonb_build_object(
      'ok',false,
      'status','conflict',
      'message','Database đã thay đổi trên thiết bị khác. Không ghi đè dữ liệu mới hơn.',
      'sync_id',v_sync_id,
      'family_id',v_family_id,
      'operation_id',p_operation_id,
      'base_revision',coalesce(p_base_revision,0),
      'current_revision',coalesce(v_current_revision,0),
      'change_count',v_change_count
    );

    insert into public.myb_idempotent_operations(
      family_id,operation_id,device_key,base_revision,change_count,status,result,error,attempt_count,created_at,updated_at
    ) values(
      v_family_id,p_operation_id,p_device_key,p_base_revision,v_change_count,'conflict',v_result,'revision_conflict',1,now(),now()
    ) on conflict (family_id,operation_id) do update set
      status='conflict',result=excluded.result,error='revision_conflict',attempt_count=public.myb_idempotent_operations.attempt_count+1,updated_at=now();

    return v_result;
  end if;

  insert into public.myb_idempotent_operations(
    family_id,operation_id,device_key,base_revision,change_count,status,attempt_count,created_at,updated_at
  ) values(
    v_family_id,p_operation_id,p_device_key,p_base_revision,v_change_count,'processing',1,now(),now()
  ) on conflict (family_id,operation_id) do update set
    status='processing',
    attempt_count=public.myb_idempotent_operations.attempt_count+1,
    updated_at=now(),
    error=null;

  -- Cho trigger V15.0.77 biết đây là write mới; tránh phát signal sớm/duplicate.
  perform set_config('myb.v1579_operation_id', p_operation_id::text, true);

  v_result := public.myb_relational_apply_changes_v1576(
    p_sync_id => v_sync_id,
    p_device_key => p_device_key,
    p_changes => p_changes
  );

  if coalesce((v_result->>'ok')::boolean,false) is not true then
    update public.myb_idempotent_operations
       set status='failed',result=coalesce(v_result,'{}'::jsonb),error=coalesce(v_result->>'message','apply_failed'),updated_at=now()
     where family_id=v_family_id and operation_id=p_operation_id;
    return coalesce(v_result,'{}'::jsonb) || jsonb_build_object(
      'operation_id',p_operation_id,'base_revision',p_base_revision,'current_revision',v_current_revision
    );
  end if;

  update public.myb_family_runtime_state
     set revision=revision+1,
         last_operation_id=p_operation_id,
         last_device_key=p_device_key,
         last_changed_at=now(),
         updated_at=now()
   where family_id=v_family_id
   returning revision into v_new_revision;

  v_result := coalesce(v_result,'{}'::jsonb) || jsonb_build_object(
    'ok',true,
    'status','applied',
    'runtime_version','15.0.79',
    'operation_id',p_operation_id,
    'base_revision',p_base_revision,
    'revision',v_new_revision,
    'change_count',v_change_count
  );

  update public.myb_idempotent_operations
     set status='applied',applied_revision=v_new_revision,result=v_result,error=null,applied_at=now(),updated_at=now()
   where family_id=v_family_id and operation_id=p_operation_id;

  -- Chỉ 1 signal / 1 COMMIT nghiệp vụ. Dữ liệu thật vẫn nằm ở relational tables.
  insert into public.myb_realtime_events(family_id,event_kind,revision,operation_id,created_at)
  values(v_family_id,'relational_write_v1579',v_new_revision,p_operation_id,now());

  -- Housekeeping nhẹ, không nằm trên đường scan business tables.
  if random() < 0.01 then
    delete from public.myb_idempotent_operations
     where family_id=v_family_id and created_at < now() - interval '45 days';
    delete from public.myb_realtime_events
     where family_id=v_family_id and created_at < now() - interval '30 days';
  end if;

  return v_result;
exception when others then
  begin
    insert into public.myb_idempotent_operations(
      family_id,operation_id,device_key,base_revision,change_count,status,result,error,attempt_count,created_at,updated_at
    ) values(
      v_family_id,p_operation_id,p_device_key,p_base_revision,v_change_count,'failed','{}'::jsonb,sqlerrm,1,now(),now()
    ) on conflict (family_id,operation_id) do update set
      status='failed',error=sqlerrm,attempt_count=public.myb_idempotent_operations.attempt_count+1,updated_at=now();
  exception when others then null;
  end;
  return jsonb_build_object(
    'ok',false,'status','failed','message',sqlerrm,'sync_id',v_sync_id,'family_id',v_family_id,'operation_id',p_operation_id
  );
end;
$$;

-- --------------------------------------------------------------------------
-- 5. Presence: cập nhật last_seen nhưng KHÔNG kích hoạt realtime refresh.
-- --------------------------------------------------------------------------
create or replace function public.myb_relational_presence_v1579(
  p_sync_id text default 'main',
  p_device_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sync_id text := coalesce(nullif(p_sync_id,''),'main');
  v_family_id uuid := public.myb_stable_uuid('family:' || coalesce(nullif(p_sync_id,''),'main'));
  v_device_id uuid := public.myb_stable_uuid('device:relational-write:' || coalesce(nullif(p_device_key,''),'unknown') || ':' || v_sync_id);
  v_online int := 0;
  v_total int := 0;
begin
  perform set_config('myb.v1579_presence','1',true);

  insert into public.families(id,sync_code,name,legacy_sync_id,created_at,updated_at,deleted_at)
  values(v_family_id,v_sync_id,'Mẹ Yêu Bé',v_sync_id,now(),now(),null)
  on conflict (id) do update set updated_at=now(),deleted_at=null;

  insert into public.devices(id,family_id,device_name,device_type,platform,app_version,last_seen_at,created_at,updated_at,deleted_at)
  values(v_device_id,v_family_id,coalesce(nullif(p_device_key,''),'Thiết bị'),'pwa','web','15.0.79',now(),now(),now(),null)
  on conflict (id) do update set last_seen_at=now(),app_version='15.0.79',updated_at=now(),deleted_at=null;

  select count(*)::int,
         count(*) filter(where last_seen_at >= now()-interval '3 minutes')::int
    into v_total,v_online
  from public.devices where family_id=v_family_id and deleted_at is null;

  return jsonb_build_object('ok',true,'family_id',v_family_id,'device_id',v_device_id,'device_count',v_total,'online_device_count',v_online,'server_time',now());
end;
$$;

-- --------------------------------------------------------------------------
-- 6. Integrity Guard cho dữ liệu MỚI.
-- NOT VALID = không ép quét/validate toàn bộ lịch sử ngay lúc patch.
-- PostgreSQL vẫn enforce constraint cho INSERT/UPDATE mới.
-- --------------------------------------------------------------------------
do $$
begin
  if not exists(select 1 from pg_constraint where conname='chk_myb_milk_items_amount_nonnegative_v1579') then
    alter table public.milk_items add constraint chk_myb_milk_items_amount_nonnegative_v1579
      check (amount_ml >= 0) not valid;
  end if;
  if not exists(select 1 from pg_constraint where conname='chk_myb_feed_events_nonnegative_v1579') then
    alter table public.feed_events add constraint chk_myb_feed_events_nonnegative_v1579
      check (coalesce(actual_ml,0) >= 0 and coalesce(taken_ml,0) >= 0 and coalesce(wasted_ml,0) >= 0) not valid;
  end if;
  if not exists(select 1 from pg_constraint where conname='chk_myb_feed_milk_sources_nonnegative_v1579') then
    alter table public.feed_milk_sources add constraint chk_myb_feed_milk_sources_nonnegative_v1579
      check (used_ml >= 0 and discard_ml >= 0) not valid;
  end if;
  if not exists(select 1 from pg_constraint where conname='chk_myb_milk_tx_nonnegative_standard_v1579') then
    alter table public.milk_transactions add constraint chk_myb_milk_tx_nonnegative_standard_v1579
      check (transaction_type='adjust' or ml >= 0) not valid;
  end if;
  if not exists(select 1 from pg_constraint where conname='chk_myb_health_weight_nonnegative_v1579') then
    alter table public.health_measurements add constraint chk_myb_health_weight_nonnegative_v1579
      check (weight_g is null or weight_g >= 0) not valid;
  end if;
end $$;

grant execute on function public.myb_relational_export_state_v1579(text) to anon, authenticated;
grant execute on function public.myb_relational_apply_changes_v1579(text,text,uuid,bigint,jsonb) to anon, authenticated;
grant execute on function public.myb_relational_presence_v1579(text,text) to anon, authenticated;

comment on table public.myb_family_runtime_state is 'V15.0.79 per-family optimistic concurrency revision. Relational tables remain source of truth.';
comment on table public.myb_idempotent_operations is 'V15.0.79 idempotency ledger for direct relational writes. Metadata only, no legacy JSON database.';
comment on function public.myb_relational_apply_changes_v1579(text,text,uuid,bigint,jsonb) is 'V15.0.79 guarded direct-table write: idempotency + family revision conflict protection + one realtime signal after commit.';

commit;

-- --------------------------------------------------------------------------
-- Quick verification. Các cột *_ok phải = true.
-- --------------------------------------------------------------------------
select
  to_regclass('public.myb_family_runtime_state') is not null as revision_state_ok,
  to_regclass('public.myb_idempotent_operations') is not null as idempotency_table_ok,
  exists(select 1 from pg_proc where proname='myb_relational_apply_changes_v1579') as guarded_write_rpc_ok,
  exists(select 1 from pg_proc where proname='myb_relational_export_state_v1579') as guarded_read_rpc_ok,
  exists(select 1 from pg_proc where proname='myb_relational_presence_v1579') as presence_rpc_ok,
  exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='myb_realtime_events') as realtime_publication_ok;
