-- ============================================================================
-- Mẹ Yêu Bé V15.0.77 · RelationalRealtimeDatabaseFirst
-- Database remains the ONLY source of truth.
-- This patch adds a tiny change-signal table for Supabase Realtime.
-- No business payload / legacy JSON is transmitted through realtime.
-- Safe to run more than once.
-- ============================================================================

begin;

create table if not exists public.myb_realtime_events (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  event_kind text not null default 'relational_write',
  created_at timestamptz not null default now()
);

create index if not exists idx_myb_realtime_events_family_id_id
  on public.myb_realtime_events(family_id, id desc);
create index if not exists idx_myb_realtime_events_created_at
  on public.myb_realtime_events(created_at desc);

-- Realtime subscribers use the anon/publishable key in the current app.
-- Only family UUID + signal timestamp are visible here; there is NO care/milk/health/device payload.
alter table public.myb_realtime_events enable row level security;
drop policy if exists myb_realtime_events_read_signal on public.myb_realtime_events;
create policy myb_realtime_events_read_signal
  on public.myb_realtime_events
  for select
  to anon, authenticated
  using (true);

revoke insert, update, delete on public.myb_realtime_events from anon, authenticated;
grant select on public.myb_realtime_events to anon, authenticated;

-- Every direct-table write batch (V15.0.76+) upserts public.devices once.
-- Emit exactly one lightweight signal in the SAME transaction. Realtime only
-- publishes it after COMMIT, so receiving devices always refetch committed data.
create or replace function public.myb_emit_relational_realtime_v1577()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.myb_realtime_events(family_id, event_kind, created_at)
  values (new.family_id, 'relational_write', now());

  -- Bounded housekeeping: once per ~100 signals, remove old signal metadata.
  if random() < 0.01 then
    delete from public.myb_realtime_events where created_at < now() - interval '30 days';
  end if;
  return new;
end;
$$;

revoke all on function public.myb_emit_relational_realtime_v1577() from public;

drop trigger if exists trg_myb_devices_realtime_v1577 on public.devices;
create trigger trg_myb_devices_realtime_v1577
after insert or update of last_seen_at on public.devices
for each row
execute function public.myb_emit_relational_realtime_v1577();

-- Enable this lightweight signal table in Supabase Postgres Changes.
do $$
begin
  if exists (select 1 from pg_publication where pubname='supabase_realtime') then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname='supabase_realtime'
        and schemaname='public'
        and tablename='myb_realtime_events'
    ) then
      execute 'alter publication supabase_realtime add table public.myb_realtime_events';
    end if;
  else
    raise notice 'Publication supabase_realtime not found. Enable Realtime for public.myb_realtime_events in Supabase Dashboard.';
  end if;
end $$;

comment on table public.myb_realtime_events is
'V15.0.77 lightweight realtime signal only. Business data remains in relational tables and clients refetch via myb_relational_export_state_v1576.';
comment on function public.myb_emit_relational_realtime_v1577() is
'Emits one no-payload realtime signal whenever a direct relational write batch updates devices.last_seen_at.';

commit;

-- Quick result: all rows below should be true/present.
select
  to_regclass('public.myb_realtime_events') is not null as realtime_table_ok,
  exists(
    select 1 from pg_trigger
    where tgname='trg_myb_devices_realtime_v1577' and not tgisinternal
  ) as trigger_ok,
  exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='myb_realtime_events'
  ) as publication_ok;
